### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by MarcosPinilla** [aruppi/animeflv#3]
502: BAD_GATEWAY
Code: NO_RESPONSE_FROM_FUNCTION
ID: gru1::9tb49-1593213470974-6a2a99d3d41e

LatestEpisodesAdded and more

**Comment by Jeluchu** [comment]
Hi @MarcosPinilla!

First I regret the delay in the response, GitHub had not notified me of the issue that you created.

We have made an update in the last days. There were problems with Cloudflare in the API, but in principle there should be no problems at the moment. The call you are telling us already works correctly

`GET: https://animeflv-six.now.sh/api/v1/LatestEpisodesAdded`

What are the others that fail exactly?

**Comment by jjarroyo** [comment]
hola me sigue saliendo el error q reportan aqui

An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION

https://animeflv-six.now.sh/api/v1/DownloadLinksByEpsId/45505/kenka-banchou-otome-5

**Comment by Jeluchu** [comment]
¡Hola @jjarroyo !

Revisaré la función que me comentas, por otra parte es cierto que actualmente la API está alojada en Vercel, y tienen un tiempo máximo para que la función responda (10 seg), es por eso que comenzamos también a desarrollar [Aruppi API](https://github.com/aruppi/aruppi-api) que son los servicios que usa la aplicación que hemos desarrollado de anime [Aruppi: Anime, Manga y Japón](https://play.google.com/store/apps/details?id=com.jeluchu.aruppi). De todos modos como bien me comentas intentaré ver el fallo que tiene esa función para poder arreglarlo lo antes posible.

Si encontrases alguna otra que falle no dudes en añadirlo en el hilo

<img src="https://i.pinimg.com/originals/ed/e3/7f/ede37f0f8ed12306b61eb24538be8ed2.gif" width="100%" alt="">

**Comment by jjarroyo** [comment]
Hola @Jeluchu  no se si es porque animeflv esta con un error de certificado pero todos los endpoint para traer anime estan fallando estaré atento a una pronta solución

Gracias

**Comment by Jeluchu** [comment]
¡Buenas de nuevo @jjarroyo !

Pues no te digo yo que no pueda ser en parte por eso por lo que no funcione, ya que en sí la API está preparada para pasar el tema de Cloudflare que suelen habilitar en ciertas ocasiones. Es probable que por el tema de los certificados falle la carga de datos, de todos modos como te comentaba, la otra API que hemos preparado para la app móvil al menos está cargando datos de hace un par de días, debe ser que hay problemas en ese aspecto, he probado a hacer la llamada de los últimos episodios añadidos y este es el log:

```
[GET] /api/v1/LatestEpisodesAdded
16:33:03:10
2020-07-18T14:33:34.065Z	bde20f57-cb97-4150-9704-f622f2b715d0	ERROR	RequestError: Response code 503 (Service Temporarily Unavailable)
    at onResponse (/var/task/node_modules/got/dist/source/as-promise/index.js:120:28)
    at onResponse (/var/task/node_modules/got/dist/source/as-promise/index.js:120:28)
    at onResponse (/var/task/node_modules/got/dist/source/as-promise/index.js:120:28)
    at onResponse (/var/task/node_modules/got/dist/source/as-promise/index.js:120:28)
    at onResponse (/var/task/node_modules/got/dist/source/as-promise/index.js:120:28)
    at onResponse (/var/task/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1595082783294,
    socket: 1595082783295,
    lookup: 1595082783298,
    connect: 1595082783300,
    secureConnect: 1595082783312,
    upload: 1595082783312,
    response: 1595082783336,
    end: 1595082783363,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 3,
      tcp: 2,
      tls: 12,
      request: 0,
      firstByte: 24,
      download: 27,
      total: 69
    }
  }
}
2020-07-18T14:38:03.291Z bde20f57-cb97-4150-9704-f622f2b715d0 Task timed out after 300.10 seconds
```
Ya para empezar da un **Task timed out after 300.10 seconds** pero como bien dices puede ser por culpa del certificado de seguridad, estaré revisando a ver que recibo al realizar la llamada a la web y si hay alguna forma de saltarse el mensaje de seguridad y acceder directamente a los datos.

**Comment by jjarroyo** [comment]
vale @Jeluchu quedo atento a cualquier novedad y si logro ya tener todo estabilizado con esta api  analizo la  Aruppi API a ver que tal 

Gracias

**Comment by Jeluchu** [comment]
@jjarroyo tengo novedades, he estado revisando el código y en principio no hay problema con el tema de los certificados de seguridad, pero si con **Cloudflare**, al parecer han cambiado el challenge que tienen al acceder a la página y es lo que está dando problemas. Actualmente para esto uso el módulo de [Hooman](https://github.com/sayem314/hooman) que hasta ahora lo mantenían actualizado y conseguía realizar el challenge sin problema, pero estamos a la espera de nueva update o algo.

Anteriormente usaba otro módulo, [Cloudscraper](https://github.com/codemanki/cloudscraper), pero la persona que se encargaba de ello lo ha dado por obsoleto, y ya no vale.

Así que actualmente el problema es el tema del challenge de **Cloudflare** y el tema del bypass, no sé si @jjarroyo sabes algo de ello y podrías ayudarme (la verdad es que desde que estoy con esta API, es lo que más quebraderos de cabeza da, los challenges de **Cloudflare**)

**Comment by jjarroyo** [comment]
ya se soluciono pero ahora al traer los servidores de descarga no trae el links si no solo los nombres de los seervidores depronto algo cambio en la estructura html cuando puedas @Jeluchu lo revisas
{
    "downloads": [
        {
            "server": "Stape"
        },
        {
            "server": "Zippyshare"
        },
        {
            "server": "MEGA"
        }
    ]
}
llega asi

**Comment by Jeluchu** [comment]
Si,  eso parece, por el momento han desactivado el tema de Cloudflare, y todo parece estar de nuevo en orden. Vale, revisaré lo que me comentas, en cuánto vea que está solucionado para subir nueva versión te comento

**Comment by Jeluchu** [comment]
@jjarroyo como ya te he comentado por privado ya está solucionado la llamada de los enlaces de descarga, para cualquier otro problema no dudéis en abrir una nueva incidencia o contactar conmigo. Cierro la incidencia
